---
base_setup_target_paths: >-
  {{ (base_setup_backup_targets | map(attribute='name')
      | map('regex_replace', '^', '/etc/btrfs-backup/') | map('regex_replace', '$', '.conf') | list)
     + (base_setup_backup_targets | map(attribute='name')
      | map('regex_replace', '^', '/var/lib/node-textfile/backup-') | map('regex_replace', '$', '.prom') | list) }}
