---
base_setup_services: []

base_setup_btrfs_snapshot_retention_days: 30

base_setup_snapshot_time: "00:00"
base_setup_restic_time: "01:00"
base_setup_update_time: "02:00"
base_setup_reboot_time: "03:00"

base_setup_backup_targets: []
base_setup_backup_retention_days: 90

base_setup_iscsi_portal: ""
base_setup_iscsi_target: ""
base_setup_iscsi_initiator: "iqn.2026-01.local.homeserver:{{ inventory_hostname }}"
base_setup_luks_passphrase: ""

base_setup_restic_repository: ""
base_setup_restic_password: ""
base_setup_restic_env: {}
base_setup_restic_image: "docker.io/restic/restic:0.19.1@sha256:136600b6ff6843d61d355f7f71f460a166429f35de6fd11b568fece3c9a4d510"
